"""
Reporter Agent — Phase 5 of the Autonomous Invention Engine.

Responsibilities:
- Aggregate artifacts from a workflow run
- Generate a structured Markdown run report
- Write to the docs/ directory for GitHub Pages publishing
"""

from __future__ import annotations

import argparse
import json
import os
from datetime import datetime, timezone
from pathlib import Path


# ── Helpers ───────────────────────────────────────────────────────────────────

def _load_json(path: Path) -> dict | list | None:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:  # noqa: BLE001
        return None


def _render_markdown(run_id: str, artifacts_dir: Path) -> str:
    now = datetime.now(timezone.utc).isoformat()

    # Try to load sub-artifacts
    discovery_data = _load_json(artifacts_dir / "discovery_index.json")
    scorecard_data = _load_json(artifacts_dir / "idea_scorecard.json")
    tap_data = _load_json(artifacts_dir / "tap_report.json")

    lines: list[str] = [
        f"# Autonomous Engine Run — `{run_id}`",
        "",
        f"**Generated**: {now}  ",
        f"**Run ID**: `{run_id}`",
        "",
        "---",
        "",
    ]

    # Discovery summary
    lines += [
        "## 📡 Discovery",
        "",
    ]
    if isinstance(discovery_data, list):
        lines.append(f"- **Signals collected**: {len(discovery_data)}")
        langs = {}
        for sig in discovery_data:
            lang = sig.get("language", "unknown")
            langs[lang] = langs.get(lang, 0) + 1
        if langs:
            lines.append("- **Languages**: " + ", ".join(f"{k} ({v})" for k, v in sorted(langs.items())))
    else:
        lines.append("_Discovery data not available._")
    lines.append("")

    # Scoring summary
    lines += ["## 📊 Scoring", ""]
    if isinstance(scorecard_data, list):
        above = [s for s in scorecard_data if s.get("score", 0) >= 0.6]
        lines.append(f"- **Total scored**: {len(scorecard_data)}")
        lines.append(f"- **Above threshold (≥0.6)**: {len(above)}")
        if above:
            lines.append("")
            lines.append("| Title | Score |")
            lines.append("|-------|-------|")
            for item in above[:10]:
                lines.append(f"| {item.get('title', 'N/A')} | {item.get('score', 0):.3f} |")
    else:
        lines.append("_Scoring data not available._")
    lines.append("")

    # TAP validation summary
    lines += ["## 🛡️ TAP Validation", ""]
    if isinstance(tap_data, dict):
        passed = tap_data.get("passed", False)
        lines.append(f"- **Result**: {'✅ Passed' if passed else '❌ Failed'}")
        summary = tap_data.get("summary", {})
        lines.append(f"- **Checks**: {summary.get('passed', 0)}/{summary.get('total', 0)} passed")
        for check in tap_data.get("checks", []):
            icon = "✅" if check.get("ok") else "❌"
            lines.append(f"  - {icon} {check.get('name')}: {check.get('message')}")
    else:
        lines.append("_TAP report not available._")
    lines.append("")

    lines += [
        "---",
        "",
        "_This report was auto-generated by the Infinity Autonomous Engine._",
    ]

    return "\n".join(lines)


# ── Main ─────────────────────────────────────────────────────────────────────

def main() -> None:
    parser = argparse.ArgumentParser(description="Reporter Agent")
    parser.add_argument("--run-id", required=True, help="GitHub Actions run ID")
    parser.add_argument("--artifacts-dir", required=True, help="Path to downloaded artifacts")
    parser.add_argument("--output", required=True, help="Directory to write report(s)")
    args = parser.parse_args()

    artifacts_dir = Path(args.artifacts_dir)
    output_dir = Path(args.output)
    output_dir.mkdir(parents=True, exist_ok=True)

    report_md = _render_markdown(args.run_id, artifacts_dir)

    report_path = output_dir / f"run-{args.run_id}.md"
    report_path.write_text(report_md, encoding="utf-8")
    print(f"[reporter] Report written to {report_path}")

    # Keep an index of reports
    index_path = output_dir / "index.md"
    existing = index_path.read_text(encoding="utf-8") if index_path.exists() else "# Run Reports\n\n"
    if f"run-{args.run_id}" not in existing:
        now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
        link_line = f"- [{now} — Run `{args.run_id}`](run-{args.run_id}.md)\n"
        # Prepend the new link after the heading
        parts = existing.split("\n\n", 1)
        updated = parts[0] + "\n\n" + link_line + (parts[1] if len(parts) > 1 else "")
        index_path.write_text(updated, encoding="utf-8")
        print(f"[reporter] Index updated at {index_path}")


if __name__ == "__main__":
    main()
