#!/usr/bin/env bash
# Rehydrate Script - Generates .infinity/ACTIVE_MEMORY.md
# This script captures the current state of the repository so the Overseer-Prime
# AI agent can synchronize its context before generating any response.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUTPUT_FILE="${REPO_ROOT}/.infinity/ACTIVE_MEMORY.md"
TIMESTAMP="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

log_info() { echo -e "${GREEN}[REHYDRATE]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[REHYDRATE]${NC} $1"; }

# Ensure output directory exists
mkdir -p "$(dirname "$OUTPUT_FILE")"

log_info "Generating ACTIVE_MEMORY.md at: $OUTPUT_FILE"

# Gather tool versions
BASH_VER="${BASH_VERSION:-unknown}"
GIT_VER="$(git --version 2>/dev/null | awk '{print $3}' || echo 'not found')"
JQ_VER="$(jq --version 2>/dev/null || echo 'not found')"
GH_VER="$(gh --version 2>/dev/null | head -1 | awk '{print $3}' || echo 'not found')"

# Gather git context
GIT_BRANCH="$(git -C "$REPO_ROOT" rev-parse --abbrev-ref HEAD 2>/dev/null || echo 'unknown')"
GIT_SHA="$(git -C "$REPO_ROOT" rev-parse --short HEAD 2>/dev/null || echo 'unknown')"
GIT_REMOTE="$(git -C "$REPO_ROOT" remote get-url origin 2>/dev/null || echo 'unknown')"

# Read orchestrator config summary
ORG_NAME="$(grep -E '^\s+organization:' "$REPO_ROOT/config/orchestrator.yml" 2>/dev/null | awk -F'"' '{print $2}' | sed 's/\${.*:-//' | sed 's/}//' || echo 'Infinity-X-One-Systems')"
DISCOVERY_INTERVAL="$(grep -A3 '^discovery:' "$REPO_ROOT/config/orchestrator.yml" 2>/dev/null | grep 'scan_interval' | awk -F'"' '{print $2}' || echo 'unknown')"
MAX_PARALLEL="$(grep 'max_parallel:' "$REPO_ROOT/config/orchestrator.yml" 2>/dev/null | head -1 | awk '{print $2}' || echo 'unknown')"

# Repository count from manifest
REPO_COUNT="unknown"
ACTIVE_COUNT="unknown"
if [ -f "$REPO_ROOT/config/repositories.json" ] && command -v jq &>/dev/null; then
    REPO_COUNT="$(jq '.statistics.total_repositories // "unknown"' "$REPO_ROOT/config/repositories.json" 2>/dev/null || echo 'unknown')"
    ACTIVE_COUNT="$(jq '.statistics.active_repositories // "unknown"' "$REPO_ROOT/config/repositories.json" 2>/dev/null || echo 'unknown')"
fi

# Org repo index summary
ORG_INDEX_UPDATED="(pending first run)"
ORG_INDEX_TOTAL="—"
ORG_INDEX_ACTIVE="—"
if [ -f "$REPO_ROOT/.infinity/ORG_REPO_INDEX.json" ] && command -v jq &>/dev/null; then
    ORG_INDEX_UPDATED="$(jq -r '.last_updated // "(unknown)"' "$REPO_ROOT/.infinity/ORG_REPO_INDEX.json" 2>/dev/null || echo '(unknown)')"
    ORG_INDEX_TOTAL="$(jq -r '.statistics.total // "—"' "$REPO_ROOT/.infinity/ORG_REPO_INDEX.json" 2>/dev/null || echo '—')"
    ORG_INDEX_ACTIVE="$(jq -r '.statistics.active // "—"' "$REPO_ROOT/.infinity/ORG_REPO_INDEX.json" 2>/dev/null || echo '—')"
fi

# Endpoint registry summary
ENDPOINT_REGISTRY_VERSION="(not found)"
ENDPOINT_REGISTRY_CATEGORIES="—"
if [ -f "$REPO_ROOT/.infinity/connectors/endpoint-registry.json" ] && command -v jq &>/dev/null; then
    ENDPOINT_REGISTRY_VERSION="$(jq -r '.version // "(unknown)"' "$REPO_ROOT/.infinity/connectors/endpoint-registry.json" 2>/dev/null || echo '(unknown)')"
    ENDPOINT_REGISTRY_CATEGORIES="$(jq '.categories | keys | length' "$REPO_ROOT/.infinity/connectors/endpoint-registry.json" 2>/dev/null || echo '—')"
fi

# Build file tree (non-hidden, max depth 3)
FILE_TREE="$(find "$REPO_ROOT" \
    -maxdepth 3 \
    -not -path '*/.git/*' \
    -not -path '*/.git' \
    -not -path '*/node_modules/*' \
    -not -path '*/__pycache__/*' \
    | sort \
    | sed "s|$REPO_ROOT/||" \
    | sed "s|$REPO_ROOT||" \
    | grep -v '^$' \
    | sed 's|[^/]*/|  |g; s|  \([^/]*\)$|  └─ \1|' \
    2>/dev/null || echo '  (unable to generate tree)')"

# Workflow list
WORKFLOW_LIST="$(find "$REPO_ROOT/.github/workflows" -name '*.yml' -o -name '*.yaml' 2>/dev/null \
    | sort \
    | sed "s|$REPO_ROOT/.github/workflows/||" \
    | sed 's/^/  - /' \
    || echo '  (none found)')"

# Script list
SCRIPT_LIST="$(find "$REPO_ROOT/scripts" -name '*.sh' -o -name '*.ps1' 2>/dev/null \
    | sort \
    | sed "s|$REPO_ROOT/scripts/||" \
    | sed 's/^/  - /' \
    || echo '  (none found)')"

cat > "$OUTPUT_FILE" << MEMEOF
# ACTIVE_MEMORY.md — Infinity Orchestrator State Snapshot
> Auto-generated by \`scripts/rehydrate.sh\`. **Do not edit manually.**
> Last updated: ${TIMESTAMP}

---

## 🗂️ Repository Identity

| Field | Value |
|-------|-------|
| Repository | infinity-orchestrator |
| Organization | Infinity-X-One-Systems |
| Remote | ${GIT_REMOTE} |
| Branch | ${GIT_BRANCH} |
| Commit SHA | ${GIT_SHA} |
| Snapshot Time | ${TIMESTAMP} |

---

## 🔧 Tool Versions

| Tool | Version |
|------|---------|
| Bash | ${BASH_VER} |
| Git | ${GIT_VER} |
| jq | ${JQ_VER} |
| GitHub CLI | ${GH_VER} |

---

## ⚙️ Active Configuration Summary

| Setting | Value |
|---------|-------|
| Organization | ${ORG_NAME} |
| Discovery Interval | ${DISCOVERY_INTERVAL} |
| Max Parallel Builds | ${MAX_PARALLEL} |
| Total Repositories (manifest) | ${REPO_COUNT} |
| Active Repositories (manifest) | ${ACTIVE_COUNT} |

---

## 📁 Repository File Tree

\`\`\`
infinity-orchestrator/
${FILE_TREE}
\`\`\`

---

## 🔄 GitHub Actions Workflows

${WORKFLOW_LIST}

---

## 🛠️ Scripts

${SCRIPT_LIST}

---

## 📋 Core Configuration Files

- \`config/orchestrator.yml\` — System-wide orchestrator settings
- \`config/repositories.json\` — Auto-generated repository manifest (updated every 6 hours)

---

## 🗄️ Org Repo Index

| Field | Value |
|-------|-------|
| Last updated | ${ORG_INDEX_UPDATED} |
| Total repositories | ${ORG_INDEX_TOTAL} |
| Active repositories | ${ORG_INDEX_ACTIVE} |

Files: \`.infinity/ORG_REPO_INDEX.json\` (machine-readable) · \`.infinity/ORG_REPO_INDEX.md\` (human-readable)  
Refresh workflow: \`.github/workflows/org-repo-index.yml\` (every 6 hours)

---

## 🔌 Endpoint Registry

| Field | Value |
|-------|-------|
| Registry version | ${ENDPOINT_REGISTRY_VERSION} |
| Categories | ${ENDPOINT_REGISTRY_CATEGORIES} |

Files: \`.infinity/connectors/endpoint-registry.json\` · \`.infinity/connectors/endpoint-registry.md\` · \`.infinity/connectors/auth-matrix.md\`

---

## 🛡️ Governance (TAP Protocol)

- Policy: \`.infinity/policies/tap-protocol.md\`
- Enforcement runbook: \`.infinity/runbooks/governance-enforcement.md\`
- Memory sync runbook: \`.infinity/runbooks/memory-sync.md\`
- Active rules: P-001 (no secrets in logs) · P-003 (bot attribution) · P-005 (App tokens only) · P-007 (graceful memory degradation)

---

## 🤖 Agent Bootstrap

Run \`.infinity/scripts/Invoke-InfinityAgentBootstrap.ps1\` to emit a structured JSON bootstrap payload.
The script is defensive and idempotent — it degrades gracefully if local memory is absent, preferring GitHub-first retrieval when App credentials are available.

---

## 🧠 Memory Protocol Notes

This file is the **single source of truth** for the Overseer-Prime agent's workspace context.

- If this file is **missing or empty**, run \`scripts/rehydrate.sh\` (Bash) or \`Run_Memory_Script.ps1\` (PowerShell).
- If workflows fail, check \`.github/workflows/rehydrate.yml\` for the auto-regeneration job.
- Configuration changes in \`config/orchestrator.yml\` are reflected here after the next rehydration.

---

*Generated by the Infinity Orchestrator rehydration system.*
MEMEOF

log_info "ACTIVE_MEMORY.md generated successfully."
log_info "Snapshot timestamp: ${TIMESTAMP}"
